version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: backtorl
      POSTGRES_PASSWORD: backtorl
      PGDATA: /var/lib/postgresql/data/mydata
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data/mydata


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080