name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#      - uses: actions/cache@v2.1.1
#        with:
#          path: "./node_modules/*"
#          key: package.json

      # NPM Install TODO: Implement Cache
      - name: NPM Install
        run: npm install
        working-directory: ./client

      - name: Build client
        run: npm run build
        working-directory: ./client

      - name: Run tests
        run: npm run test
        working-directory: ./client

#      - name: Run linter
#        run: npm run lint
#        working-directory: ./client
